config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  use_doorkeeper
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'home'   => 'static_pages#home'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :people
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match ':controller(/:action(/:id(.:format)))', :via => :all
  resources :events
  root 'welcome#index'
  get 's' => 'welcome#index'
  get 'req' => 'welcome#req'
  get 'res' => 'welcome#res'
  get 't' => 'welcome#tests'
  get 'dir' => 'welcome#dirs'
  get 'test' => 'tests#index'
  get 'redis' => 'cache#redis'

  #api route
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      scope path: '/user/:user_id' do
        resources :microposts, only: [:index]
      end
      # 原文有 microposts, 我们现在把它注释掉
      # resources :microposts, only: [:index, :create, :show, :update, :destroy]
    end

    namespace :v2 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      scope path: '/user/:user_id' do
        resources :microposts, only: [:index]
      end
    end
    
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :name
end

app/models/item.rb
class Item < ApplicationRecord
	self.primary_key = "id"
	self.table_name = "items"
	
	# will_paginate
	# self.per_page = 10
	
	# kaminari 
	paginates_per 8
end

app/models/micropost.rb
class Micropost < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord	
	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_many :microposts
	has_secure_password
	# 转换成小写
	before_save { self.email = email.downcase }
	before_create :generate_authentication_token
	def generate_authentication_token
		loop do
			self.authentication_token = SecureRandom.base64(64)
			break if !User.find_by(authentication_token: authentication_token)
		end
	end

	def reset_auth_token!
		generate_authentication_token
		save
	end
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController
	def redis
		@redis = Redis.new(:url => "redis://localhost:6379/0")
	end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  USER_NAME, PASSWORD = 'doc_reader', '123123'
  before_filter :basic_authenticate
  layout false
  def index
  
  end

  private

  def basic_authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == USER_NAME && password == PASSWORD
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
		# @events = Event.page(params[:page]).per(5)

		respond_to do |format|
			format.html # index.html.erb
			format.xml { render :xml => @events.to_xml }
			format.json { render :json => @events.to_json }
			format.atom { @feed_title = "My event list" } # index.atom.builder
		end
	end

	def new
		@event = Event.new		
	end

	def create
		#@event = Event.new(params[:event])
		@event = Event.new(event_params)
		@event.save
		redirect_to :action => :index
	end

	def show
		# @event = Event.find(params[:id])
		@event = Event.find(params[:id])
		respond_to do |format|
			format.html { @page_title = @event.name } # show.html.erb
			format.xml # show.xml.builder
			format.json { render :json => { id: @event.id, name: @event.name }.to_json }
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		@event.update(event_params)
		#redirect_to :action => :show, :id => @event
		redirect_to event_url(@event)
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		#redirect_to :action => :index
		redirect_to event_url(@event)
	end

	#private
	def event_params
		params.require(:event).permit(:name, :description)
	end

	private :event_params
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		# @items = Item.all
		# @items = Item.take(20)
		# @items = Item.first(15)
		# require 'will_pagkaminariinate'
		# paginate在helper已重新定义
		# @items = Item.paginate(:page => params[:page], :per_page => 8)
		
		# kaminari
		@items = Item.order(:id).page params[:page]
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	def index
		render html: 'html render'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 处理注册成功的情况
      flash[:success] = "注册成功!"
      redirect_to @user
      # redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  private
	  def user_params
	    params.require(:user).permit(:name, :email, :password,:password_confirmation)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def paginate_meta_attributes(json, object)
		# json.(object,:current_page,:next_page,:prev_page,:total_pages,:total_count)
		json.(object,
          :current_page,
          :next_page,
          :prev_page,
          :total_pages,
					:total_count)
	end
end

app/helpers/cache_helper.rb
module CacheHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# 登入指定的用户
  def log_in(user)
    session[:user_id] = user.id
  end
  # 返回当前登录的用户（如果有的话）
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # 如果用户已登录，返回 true，否则返回 false
  def logged_in?
    !current_user.nil?
  end
  # 退出当前用户
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 返回指定用户的 Gravatar
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %>
      <%= link_to " (XML)", event_path(event, :format => :xml) %>
      <%= link_to " (JSON)", event_path(event, :format => :json) %>
      <%= link_to 'edit', edit_event_path(event) %>
      <%= button_to 'delete', event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </li>
<% end %>
</ul>

<%= link_to 'new event', new_event_path %>
<%= link_to "Atom feed", events_path(:format => :atom) %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= debug(@event) %>
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="table table-striped">
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Address</th>
        </tr>

        <% @items.each do |i| %>
            <tr>
              <td><%= i.id %></td>
              <td><%= i.name %></td>
              <td><%= i.email %></td>
              <td><%= i.address %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="digg_pagination">
    <%#= will_paginate @items, :container => true %>
    <%= paginate @items, :window => 2 %>
  </div>
 </div>