config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  use_doorkeeper
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'home'   => 'static_pages#home'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :people
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match ':controller(/:action(/:id(.:format)))', :via => :all
  resources :events
  root 'welcome#index'
  get 's' => 'welcome#index'
  get 'req' => 'welcome#req'
  get 'res' => 'welcome#res'
  get 't' => 'welcome#tests'
  get 'dir' => 'welcome#dirs'
  get 'test' => 'tests#index'
  get 'redis' => 'cache#redis'

  #api route
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      scope path: '/user/:user_id' do
        resources :microposts, only: [:index]
      end
      # 原文有 microposts, 我们现在把它注释掉
      # resources :microposts, only: [:index, :create, :show, :update, :destroy]
    end

    namespace :v2 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      scope path: '/user/:user_id' do
        resources :microposts, only: [:index]
      end
    end
    
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :name
end

app/models/item.rb
class Item < ApplicationRecord
	self.primary_key = "id"
	self.table_name = "items"
	
	# will_paginate
	# self.per_page = 10
	
	# kaminari 
	paginates_per 8
end

app/models/micropost.rb
class Micropost < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord	
	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_many :microposts
	has_secure_password
	# 转换成小写
	before_save { self.email = email.downcase }
	before_create :generate_authentication_token
	def generate_authentication_token
		loop do
			self.authentication_token = SecureRandom.base64(64)
			break if !User.find_by(authentication_token: authentication_token)
		end
	end

	def reset_auth_token!
		generate_authentication_token
		save
	end
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController
	def redis
		@redis = Redis.new(:url => "redis://localhost:6379/0")
	end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  USER_NAME, PASSWORD = 'doc_reader', '123123'
  before_filter :basic_authenticate
  layout false
  def index
  
  end

  private

  def basic_authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == USER_NAME && password == PASSWORD
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		# @items = Item.all
		# @items = Item.take(20)
		# @items = Item.first(15)
		# require 'will_pagkaminariinate'
		# paginate在helper已重新定义
		# @items = Item.paginate(:page => params[:page], :per_page => 8)
		
		# kaminari
		@items = Item.order(:id).page params[:page]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def paginate_meta_attributes(json, object)
		# json.(object,:current_page,:next_page,:prev_page,:total_pages,:total_count)
		json.(object,
          :current_page,
          :next_page,
          :prev_page,
          :total_pages,
					:total_count)
	end
end

app/helpers/cache_helper.rb
module CacheHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# 登入指定的用户
  def log_in(user)
    session[:user_id] = user.id
  end
  # 返回当前登录的用户（如果有的话）
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # 如果用户已登录，返回 true，否则返回 false
  def logged_in?
    !current_user.nil?
  end
  # 退出当前用户
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 返回指定用户的 Gravatar
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
			  <span class="sr-only">Toggle navigation</span>
			  <span class="icon-bar"></span>
			  <span class="icon-bar"></span>
			  <span class="icon-bar"></span>
			</button>
			<a class="navbar-brand hidden-sm" href="#">rails5 Simple App</a>
		</div>
		<div class="navbar-collapse collapse" role="navigation">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", home_path %></li>
				<li><%= link_to "about", about_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right hidden-sm">
				<li><a href="/events/">event路由</a></li>
			</ul>
		</div>
	</div>
</div>

<!-- <div class="center jumbotron">
  <h1>bootstrap jumbotron component</h1>
  <h2>
    这是首页展示组件
    <a href="http://ruby-china.org/">rails5</a>
    sample app.
  </h2>
  <%= link_to "主页链接...!", '#', class: "btn btn-lg btn-primary" %>
</div>
<p class="version">
	<strong>Rails version:</strong> <%= Rails.version %><br />
  <strong>Ruby version:</strong> <%= RUBY_VERSION %> (<%= RUBY_PLATFORM %>)
</p>
<%= link_to image_tag("rails.png", alt: "Rails logo"),'http://rubyonrails.org/' %> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/shim' %>
  </head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
	  <%= yield %>
	  <%= debug(params) if Rails.env.development? %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>